thread:
  pool:
# 日志打印,这里的alive time单位是s
    log:
      queueSize: 1000
      corePoolSize:  2
      maximumPoolSize: 5
      keepAliveTime:  10

# netty 线程设置
  bootstrap:
    worker: 20
    boss: 1

# 执行定时任务
    schedule:
      queueSize: 50
      corePoolSize:  2
      maximumPoolSize: 5
      keepAliveTime:  0

# 最重要的一个线程池，可以根据业务去调整线程池大小,这里的alive time单位是s
    chief:
      queueSize: 2000
      corePoolSize:  4
      maximumPoolSize: 20
      keepAliveTime:  60
